### ISSUE TITLE
Misaligned pointer read of fdt_reserve_entry

### ISSUE THREAD

**Issue by spwilson2** [rs-embedded/fdt-rs#16]
Issue stems from my faulty assertion that structs would be 32-bit aligned. (The fdt_reserve_entry is 64-bit aligned since its members are uniquely 64be typed.)

Unfortunately, because the API returns a reference to each parsed field the API to access this field will need to change. (We can't return a misaligned reference.) Since internally this isn't a particularly widely used field, API blowback should be minimal.

We should either return a special wrapper that supports misaligned references/raw pointers or just return a raw pointer and have the consumer deal with the read_unaligned call. (I'm leaning towards using a wrapper type for safety.)

```
    /// Return the current offset as a fdt_reserve_entry reference.
    ///
    /// # Safety
    ///
    /// The caller must verify that the current offset of this iterator is 32-bit aligned.
    /// (Each field is 32-bit aligned and they may be read individually.)
    unsafe fn read(&'a self) -> Result<&'dt fdt_reserve_entry> {
        Ok(&*self.fdt.ptr_at(self.offset)?)
    }
}

impl<'a, 'dt: 'a> Iterator for DevTreeReserveEntryIter<'a, 'dt> {
    type Item = &'dt fdt_reserve_entry;
    fn next(&mut self) -> Option<Self::Item> {
...
            // We guaruntee the read will be aligned to 32 bits because:
            // - We construct with guarunteed 32-bit aligned offset
            // - We always increment by an aligned amount
            let ret = unsafe { self.read().unwrap() };

...
            Some(ret)

```

```
thread 'reserved_entries_iter' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x1026398c4', src/base/iters.rs:41:12
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_misaligned_pointer_dereference
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:174:5
   3: fdt_rs::base::iters::DevTreeReserveEntryIter::read
             at ./src/base/iters.rs:41:12
   4: <fdt_rs::base::iters::DevTreeReserveEntryIter as core::iter::traits::iterator::Iterator>::next
             at ./src/base/iters.rs:54:32
   5: core::iter::traits::iterator::Iterator::fold
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:2481:29
   6: core::iter::traits::iterator::Iterator::count
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:267:9
   7: parsing_test::reserved_entries_iter
             at ./tests/parsing_test.rs:88:17
   8: parsing_test::reserved_entries_iter::{{closure}}
             at ./tests/parsing_test.rs:85:28
   9: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
```

**Comment by berkus** [comment]
So how to get size and address from device_tree.fdt().reserved_entries() now? I don't see a public api for that now, what am I missing?
